---
- name: Ensure Linux is updated
  hosts: dev-vms
  become: yes
  become_method: sudo
  tasks:
    - name: "Update APT Packages"
      apt:
      update_cache: true
      upgrade: dist
      cache_valid_time: 3600
      force_apt_get: true
